//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.6, generator: @autorest/go@4.0.0-preview.50)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package azureopenai

type ContentFilterSeverity string

const (
	// ContentFilterSeverityHigh - Harmful content at a high intensity and risk level.
	ContentFilterSeverityHigh ContentFilterSeverity = "high"
	// ContentFilterSeverityLow - Harmful content at a low intensity and risk level.
	ContentFilterSeverityLow ContentFilterSeverity = "low"
	// ContentFilterSeverityMedium - Harmful content at a medium intensity and risk level.
	ContentFilterSeverityMedium ContentFilterSeverity = "medium"
	// ContentFilterSeveritySafe - General content or related content in generic or non-harmful contexts.
	ContentFilterSeveritySafe ContentFilterSeverity = "safe"
)

// PossibleContentFilterSeverityValues returns the possible values for the ContentFilterSeverity const type.
func PossibleContentFilterSeverityValues() []ContentFilterSeverity {
	return []ContentFilterSeverity{
		ContentFilterSeverityHigh,
		ContentFilterSeverityLow,
		ContentFilterSeverityMedium,
		ContentFilterSeveritySafe,
	}
}

// InnerErrorCode - Error codes for the inner error object.
type InnerErrorCode string

const (
	// InnerErrorCodeResponsibleAIPolicyViolation - The prompt violated one of more content filter rules.
	InnerErrorCodeResponsibleAIPolicyViolation InnerErrorCode = "ResponsibleAIPolicyViolation"
)

// PossibleInnerErrorCodeValues returns the possible values for the InnerErrorCode const type.
func PossibleInnerErrorCodeValues() []InnerErrorCode {
	return []InnerErrorCode{
		InnerErrorCodeResponsibleAIPolicyViolation,
	}
}

// MessageRole - The role of the author of this message.
type MessageRole string

const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleTool      MessageRole = "tool"
	MessageRoleUser      MessageRole = "user"
)

// PossibleMessageRoleValues returns the possible values for the MessageRole const type.
func PossibleMessageRoleValues() []MessageRole {
	return []MessageRole{
		MessageRoleAssistant,
		MessageRoleSystem,
		MessageRoleTool,
		MessageRoleUser,
	}
}

// Post200ApplicationJSONPropertiesItemsMessageRole - The role of the author of this message.
type Post200ApplicationJSONPropertiesItemsMessageRole string

const (
	Post200ApplicationJSONPropertiesItemsMessageRoleAssistant Post200ApplicationJSONPropertiesItemsMessageRole = "assistant"
	Post200ApplicationJSONPropertiesItemsMessageRoleSystem    Post200ApplicationJSONPropertiesItemsMessageRole = "system"
	Post200ApplicationJSONPropertiesItemsMessageRoleUser      Post200ApplicationJSONPropertiesItemsMessageRole = "user"
)

// PossiblePost200ApplicationJSONPropertiesItemsMessageRoleValues returns the possible values for the Post200ApplicationJSONPropertiesItemsMessageRole const type.
func PossiblePost200ApplicationJSONPropertiesItemsMessageRoleValues() []Post200ApplicationJSONPropertiesItemsMessageRole {
	return []Post200ApplicationJSONPropertiesItemsMessageRole{
		Post200ApplicationJSONPropertiesItemsMessageRoleAssistant,
		Post200ApplicationJSONPropertiesItemsMessageRoleSystem,
		Post200ApplicationJSONPropertiesItemsMessageRoleUser,
	}
}

// PostRequestBodyContentApplicationJSONSchemaMessagesItemRole - The role of the author of this message.
type PostRequestBodyContentApplicationJSONSchemaMessagesItemRole string

const (
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleAssistant PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "assistant"
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleSystem    PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "system"
	PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleUser      PostRequestBodyContentApplicationJSONSchemaMessagesItemRole = "user"
)

// PossiblePostRequestBodyContentApplicationJSONSchemaMessagesItemRoleValues returns the possible values for the PostRequestBodyContentApplicationJSONSchemaMessagesItemRole const type.
func PossiblePostRequestBodyContentApplicationJSONSchemaMessagesItemRoleValues() []PostRequestBodyContentApplicationJSONSchemaMessagesItemRole {
	return []PostRequestBodyContentApplicationJSONSchemaMessagesItemRole{
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleAssistant,
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleSystem,
		PostRequestBodyContentApplicationJSONSchemaMessagesItemRoleUser,
	}
}
