//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.6, generator: @autorest/go@4.0.0-preview.50)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package azureopenai

// ChatCompletionsClientCreateResponse contains the response from method ChatCompletionsClient.Create.
type ChatCompletionsClientCreateResponse struct {
	Paths1H0F83DeploymentsDeploymentIDChatCompletionsPostResponses200ContentApplicationJSONSchema
	// ApimRequestID contains the information returned from the apim-request-id header response.
	ApimRequestID *string
}

// CompletionsClientCreateResponse contains the response from method CompletionsClient.Create.
type CompletionsClientCreateResponse struct {
	PathsMaorw9DeploymentsDeploymentIDCompletionsPostResponses200ContentApplicationJSONSchema
	// ApimRequestID contains the information returned from the apim-request-id header response.
	ApimRequestID *string
}

// EmbeddingsClientCreateResponse contains the response from method EmbeddingsClient.Create.
type EmbeddingsClientCreateResponse struct {
	Paths15Cw454DeploymentsDeploymentIDEmbeddingsPostResponses200ContentApplicationJSONSchema
}

// ExtensionsChatCompletionsClientCreateResponse contains the response from method ExtensionsChatCompletionsClient.Create.
type ExtensionsChatCompletionsClientCreateResponse struct {
	ExtensionsChatCompletionsResponse
	// ApimRequestID contains the information returned from the apim-request-id header response.
	ApimRequestID *string
}
